UPDATE KPDBA.DYMCHK_PROT
SET
  FORM_TITLE = :S_FORM_TITLE,
  FORM_CODE = :S_FORM_CODE,
  FORM_REVISION = :S_FORM_REVISION,
  ISO_DOC_CODE = :S_ISO_DOC_CODE,
  ISO_DOC_REVISION = :S_ISO_DOC_REVISION,
  FORM_DESC = :S_FORM_DESC,
  UPDATE_DATE = :S_UPDATE_DATE,
  UPDATE_OID = :S_UPDATE_OID,
  UPDATE_UID = :S_UPDATE_UID
WHERE
  PROT_ID = :S_PROT_ID AND
  CR_UID = :S_CR_UID