UPDATE KPDBA.DYMCHK_FORM_APPROVAL
SET
  TOPIC_ID = :S_TOPIC_ID,
  UPDATE_DATE = :S_UPDATE_DATE,
  UPDATE_OID = :S_UPDATE_OID,
  UPDATE_UID = :S_UPDATE_UID
WHERE
  FORM_ID = :S_FORM_ID AND
  SEQ = :S_SEQ 
