UPDATE KPDBA.DYMCHK_FORM_VALUE
SET
  TOPIC_VALUE = :S_TOPIC_VALUE,
  UPDATE_DATE = :S_UPDATE_DATE,
  UPDATE_OID = :S_UPDATE_OID,
  UPDATE_UID = :S_UPDATE_UID
WHERE
  FORM_ID = :S_FORM_ID AND
  SEQ = :S_SEQ AND
  ROW_ID = :S_ROW_ID AND
  COL_ID = :S_COL_ID AND
  TOPIC_ID = :S_TOPIC_ID 
