SELECT  PD.PROT_ID
FROM 
(
SELECT PROT_ID
FROM (
    SELECT DP.PROT_ID
    FROM  KPDBA.DYMCHK_PROT DP
    JOIN KPDBA.DYMCHK_PROT_PROP PP ON DP.PROT_ID = PP.PROT_ID
    JOIN KPDBA.SQL_TAB_SOA SS ON PP.PROP_VALUE = TO_CHAR(SS.SQL_NO)
    WHERE DP.ISO_DOC_CODE = 'FA/044'
    AND DP.APPV_FLAG = 'R'
    AND NVL(DP.CANCEL_FLAG, 'F') = 'F'
    AND PP.PROP_TYPE = 'sqlTabText' 
    AND SS.SQL_NO BETWEEN 700790001 AND 700799999
    AND SS.SQL_DESC = 'เครื่องพิมพ์'
    ORDER BY DP.ISO_DOC_REVISION DESC
) 
WHERE ROWNUM = 1
) PD
FULL OUTER JOIN
(
SELECT PROT_ID
FROM (
    SELECT DP.PROT_ID
    FROM KPDBA.DYMCHK_PROT DP 
    JOIN KPDBA.DYMCHK_PROT_PROP PP ON DP.PROT_ID = PP.PROT_ID
    JOIN KPDBA.SQL_TAB_SOA SS ON PP.PROP_VALUE = TO_CHAR( SS.SQL_NO)
    WHERE DP.ISO_DOC_CODE = 'FA/044'
     AND DP.APPV_FLAG = 'R'
    AND NVL(DP.CANCEL_FLAG, 'F') = 'F'
    AND PP.PROP_TYPE = 'sqlTabText' 
    AND SS.SQL_NO BETWEEN 700790001 AND 700799999
    AND SS.SQL_DESC =:S_MACH_TYPE
  ORDER BY DP.UPDATE_DATE DESC
)  
WHERE ROWNUM = 1

) MC ON PD.PROT_ID = MC.PROT_ID  
WHERE PD.PROT_ID = MC.PROT_ID
GROUP BY  PD.PROT_ID