SELECT DFV.TOPIC_ID, DPT.TOPIC_TYPE,DFV.TOPIC_VALUE
FROM KPDBA.DYMCHK_FORM_USER DFU
JOIN KPDBA.DYMCHK_FORM_VALUE DFV ON DFU.FORM_ID = DFV.FORM_ID AND DFU.SEQ = DFV.SEQ
JOIN KPDBA.DYMCHK_PROT_TOPIC DPT ON DFV.TOPIC_ID = DPT.TOPIC_ID
WHERE DPT.TOPIC_TYPE = 'ApprovalField' AND  DFU.FORM_ID =:S_FORM_ID AND    DFU.SEQ = :S_SEQ
