UPDATE
  KPDBA.DYMCHK_ROLES
SET
  CANCEL_FLAG = :S_CANCEL_FLAG,
  CANCEL_USER_ID = :S_CANCEL_USER_ID,
  CANCEL_ORG_ID = :S_CANCEL_ORG_ID,
  UP_DATE = :S_UP_DATE,
  UP_USER_ID = :S_UP_USER_ID,
  UP_ORG_ID = :S_UP_ORG_ID
WHERE
  ROLE_NO = :S_ROLE_NO