SELECT DF.FORM_ID,DPT.PROT_ID,DFU.SEQ,DPT.TOPIC_ID,DPT.TOPIC_TYPE,DFV.TOPIC_VALUE
FROM 
KPDBA.DYMCHK_PROT_TOPIC  DPT
LEFT JOIN     KPDBA.DYMCHK_PROT DP ON DP.PROT_ID = DPT.PROT_ID
LEFT JOIN     KPDBA.DYMCHK_FORM DF ON DF.PROT_ID = DP.PROT_ID
LEFT JOIN     KPDBA.DYMCHK_FORM_USER DFU ON DFU.FORM_ID = DF.FORM_ID
LEFT JOIN     KPDBA.DYMCHK_FORM_VALUE DFV ON DFV.FORM_ID = DF.FORM_ID
  WHERE TOPIC_TYPE = 'SelectDBField'
    AND DF.FORM_ID = :S_FORM_ID