SELECT FU.FORM_ID,FU.SEQ,DF.PROT_ID,FU.STATUS,FU.USER_ID,DFV.MAX_UPDATE_DATE
FROM KPDBA.DYMCHK_FORM_USER FU 
JOIN KPDBA.DYMCHK_FORM DF ON FU.FORM_ID = DF.FORM_ID
JOIN (
SELECT 
    DFVR.FORM_ID,
    MAX(DFVR.UPDATE_DATE) AS MAX_UPDATE_DATE
FROM 
    KPDBA.DYMCHK_FORM_VALUE DFVR
JOIN  
    KPDBA.DYMCHK_PROT_TOPIC DPT ON DFVR.TOPIC_ID = DPT.TOPIC_ID
WHERE DPT.TOPIC_TYPE <> 'ApprovalField'
GROUP BY 
    DFVR.FORM_ID
) DFV ON FU.FORM_ID = DFV.FORM_ID 
WHERE FU.FORM_ID = :S_FORM_ID AND FU.SEQ = :S_SEQ