SELECT
    FU.FORM_ID,
    FU.SEQ,
    DF.URL,
    FU.USER_ID,
    DF.REQ_USER_FLAG,
    DF.PROT_ID,
    DF.START_DATE,
    DF.END_DATE,
    FU.STATUS AS STATUS,
    DFV.MAX_UPDATE_DATE
FROM
    KPDBA.DYMCHK_FORM_USER FU
    LEFT JOIN (
        SELECT
            DFVR.FORM_ID,
            DFVR.SEQ,
            MAX(DFVR.UPDATE_DATE) AS MAX_UPDATE_DATE
        FROM
            KPDBA.DYMCHK_FORM_VALUE DFVR
            JOIN KPDBA.DYMCHK_PROT_TOPIC DPT ON DFVR.TOPIC_ID = DPT.TOPIC_ID
        WHERE
            DPT.TOPIC_TYPE <> 'ApprovalField'
        GROUP BY
            DFVR.FORM_ID,
            DFVR.SEQ
    ) DFV ON FU.FORM_ID = DFV.FORM_ID
    AND FU.SEQ = DFV.SEQ
    LEFT JOIN KPDBA.DYMCHK_FORM DF ON FU.FORM_ID = DF.FORM_ID
WHERE
    DF.URL = :S_URL