UPDATE
    KPDBA.DYMCHK_FORM_USER
SET
    CANCEL_FLAG = :S_CANCEL_FLAG,
    CANCEL_DATE = :S_CANCEL_DATE,
    CANCEL_UID = :S_CANCEL_UID,
    CANCEL_OID = :S_CANCEL_OID,
    UPDATE_DATE = :S_UPDATE_DATE,
    UPDATE_OID = :S_UPDATE_OID,
    UPDATE_UID = :S_UPDATE_UID
WHERE
    FORM_ID = :S_FORM_ID
    AND SEQ = :S_SEQ