    SELECT
    DFV.FORM_ID,
    DFV.SEQ,
    DPT.TOPIC_TYPE,
    CASE
        WHEN TOPIC_TYPE = 'ApprovalField' THEN 'T'
        ELSE 'F' 
    END AS IS_APPROVAL
FROM
    KPDBA.DYMCHK_FORM_VALUE DFV
    LEFT JOIN KPDBA.DYMCHK_PROT_TOPIC DPT ON DFV.TOPIC_ID = DPT.TOPIC_ID
    WHERE DFV.UPDATE_UID = :S_USER_ID
    AND DPT.TOPIC_TYPE = 'ApprovalField'
GROUP BY
    DFV.FORM_ID,
    DFV.SEQ,
    DPT.TOPIC_TYPE