SELECT 
  FU.FORM_ID,
    DF.URL,
    FU.SEQ,
    FU.USER_ID,
    FU.CR_DATE,
    FU.CR_OID,
    FU.CR_UID,
    FU.UPDATE_DATE,
    FU.UPDATE_UID,
       DP.FORM_TITLE,
    DP.FORM_DESC,
     DF.START_DATE,
    DF.END_DATE,
      DP.FORM_CODE,
    DP.FORM_REVISION,
    DP.ISO_DOC_CODE,
    DP.ISO_DOC_REVISION,
    CASE WHEN FU.CANCEL_FLAG = 'T' THEN 'Canceled' ELSE FU.STATUS END AS STATUS,
    FU.CANCEL_FLAG,
    FU.CANCEL_DATE,
    FU.CANCEL_UID,
    FU.CANCEL_OID
FROM
    KPDBA.DYMCHK_FORM_USER FU
      LEFT JOIN KPDBA.DYMCHK_FORM DF ON FU.FORM_ID = DF.FORM_ID
    LEFT JOIN KPDBA.DYMCHK_PROT DP ON DF.PROT_ID = DP.PROT_ID
    WHERE
    FU.USER_ID = :S_USER_ID AND FU.CANCEL_FLAG <> 'P'