WITH FORMCOUNTS AS (
   SELECT
    FU.FORM_ID,
    FU.SEQ,
    COUNT(
        CASE
            WHEN FV.TOPIC_VALUE IS NOT NULL THEN 1
        END
    ) AS FORMITEMVALUECOUNT,
    COUNT(*) AS FORMITEMCOUNT
FROM
    KPDBA.DYMCHK_FORM_USER FU
    LEFT JOIN KPDBA.DYMCHK_FORM_VALUE FV ON FU.FORM_ID = FV.FORM_ID
    LEFT JOIN KPDBA.DYMCHK_PROT_TOPIC PT ON (FV.TOPIC_ID = PT.TOPIC_ID AND FU.SEQ = FV.SEQ)
WHERE
     PT.TOPIC_TYPE <> 'ApprovalField'
GROUP BY
    FU.FORM_ID,
    FU.SEQ
)
SELECT
    FU.FORM_ID,
    DF.URL,
    FU.SEQ,
    FU.USER_ID,
    FU.CR_DATE,
    FU.CR_OID,
    FU.CR_UID,
    FU.UPDATE_DATE,
    FU.UPDATE_UID,
    DP.FORM_TITLE,
    DP.FORM_DESC,
    DF.START_DATE,
    DF.END_DATE,
    DP.FORM_CODE,
    DP.FORM_REVISION,
    DP.ISO_DOC_CODE,
    DP.ISO_DOC_REVISION,
    FC.FORMITEMVALUECOUNT,
    FC.FORMITEMCOUNT,
    CASE
        WHEN DF.END_DATE >= CURRENT_DATE
        AND FC.FORMITEMVALUECOUNT = 0 THEN 'รอ'
        WHEN DF.END_DATE >= CURRENT_DATE
        AND FC.FORMITEMVALUECOUNT = FC.FORMITEMCOUNT THEN 'เสร็จ'
        WHEN DF.END_DATE >= CURRENT_DATE
        AND FC.FORMITEMVALUECOUNT > 0 THEN 'กำลังทำ'
        WHEN (
            (
                DF.END_DATE <= CURRENT_DATE
                AND FC.FORMITEMVALUECOUNT = FC.FORMITEMCOUNT
            )
            OR (
                DF.END_DATE <= CURRENT_DATE
                AND FC.FORMITEMVALUECOUNT > 0
            )
            OR (
                DF.END_DATE >= CURRENT_DATE
                AND FC.FORMITEMVALUECOUNT = FC.FORMITEMCOUNT
            )
        ) THEN 'เสร็จ'
        WHEN DF.END_DATE <= CURRENT_DATE THEN 'หมดเวลา'
        ELSE 'หมดเวลา'
    END AS STATUS
FROM
    KPDBA.DYMCHK_FORM_USER FU
    LEFT JOIN KPDBA.DYMCHK_FORM DF ON FU.FORM_ID = DF.FORM_ID
    LEFT JOIN KPDBA.DYMCHK_PROT DP ON DF.PROT_ID = DP.PROT_ID
    LEFT JOIN FORMCOUNTS FC ON FU.FORM_ID = FC.FORM_ID
    AND FU.SEQ = FC.SEQ
WHERE
    FU.USER_ID = :S_USER_ID